[build]
  base = "/"
  command = "yarn build"
  publish = "/dist"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Robots-Tag = "noindex"